# Generated by Django 4.1.8 on 2023-04-17 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutpage',
            options={'verbose_name': 'About Page', 'verbose_name_plural': 'About Page'},
        ),
        migrations.AlterModelOptions(
            name='callforabstractpage',
            options={'verbose_name': 'Call for Abstract', 'verbose_name_plural': 'Call for Abstracts'},
        ),
        migrations.AlterModelOptions(
            name='speakers',
            options={'verbose_name': 'Speaker', 'verbose_name_plural': 'Speakers'},
        ),
        migrations.AlterModelOptions(
            name='technicaladvisorycommittee',
            options={'verbose_name': 'Tecnical Advisory Committee', 'verbose_name_plural': 'Tecnical Advisory Committees'},
        ),
    ]
