# Generated by Django 4.1.8 on 2023-04-17 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0083_workflowcontenttype'),
        ('registration', '0002_formpage_formfield'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FormPage',
            new_name='RegistrationFormPage',
        ),
    ]
