# Generated by Django 4.1.8 on 2023-04-15 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_homepage_about_cta_homepage_banner_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='feature_conference_on_site',
        ),
    ]
