# Generated by Django 4.1.8 on 2023-04-15 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_homepage_feature_conference_on_site'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='year',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
