# Generated by Django 4.1.8 on 2023-04-17 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sponsorship', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sponsors',
            options={'verbose_name': 'Sponsor', 'verbose_name_plural': 'Sponsors'},
        ),
    ]
