# Generated by Django 4.1.8 on 2023-04-18 16:48

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('sponsorship', '0002_alter_sponsors_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sponsorshippackage',
            old_name='type',
            new_name='sponsorship_type',
        ),
        migrations.AddField(
            model_name='sponsorshippage',
            name='sponsorship_package',
            field=modelcluster.fields.ParentalKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sponsorship_package', to='sponsorship.sponsorshippackage'),
        ),
    ]
