# Generated by Django 4.1.8 on 2023-04-18 17:04

from django.db import migrations
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('sponsorship', '0003_rename_type_sponsorshippackage_sponsorship_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sponsorshippage',
            name='sponsorship_package',
        ),
        migrations.AddField(
            model_name='sponsorshippage',
            name='sponsorship_package',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, to='sponsorship.sponsorshippackage'),
        ),
    ]
