# Generated by Django 4.1.8 on 2023-04-19 23:20

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('sponsorship', '0005_sponsorformpage_sponsordetail_package_formfield_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsorformpage',
            name='package',
            field=modelcluster.fields.ParentalKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sponsor_form_package', to='sponsorship.sponsorshippackage'),
        ),
        migrations.DeleteModel(
            name='SponsorDetail',
        ),
    ]
