# Generated by Django 4.1.8 on 2023-04-20 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sponsorship', '0006_sponsorformpage_package_delete_sponsordetail'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sponsors',
        ),
    ]
